### ISSUE TITLE
[Feature Request]: AmbigNQ for CRITIC

### ISSUE THREAD

**Issue by alckasoc** [alckasoc/agential#71]
### Feature Description

Familiarize yourself with the repository and take a look the CRITIC [repo](https://github.com/microsoft/ProphetNet/tree/master/CRITIC), [paper](https://arxiv.org/abs/2305.11738), and [AmbigNQ](https://arxiv.org/abs/2004.10645).

There are 3 question answering (QA) tasks tested in the paper: HotpotQA, TriviaQA, and AmbigNQ. 

Currently, the CRITIC implementation only has [prompts](https://github.com/alckasoc/agential/blob/main/agential/cog/prompts/critic.py) for HotpotQA and TriviaQA.

Add the AmbigNQ prompts and relevant logic to the current CRITIC implementation. You'll see that an agent's current structure is divided into `cog/agent`, `cog/modules`, and `cog/functional/`. This task will require you to make modifications in `cog/prompts`, but will also require you to test your code in all the other relevant modules `cog/functional` and `cog/agent`. CRITIC does not have any `cog/modules`. 

**What to submit**:

- [x] Set up your environment via the CONTRIBUTING.md
- [x] Make a Pull Request (PR)
- [x] Add the prompts for AmbigNQ
- [x] Write a short notebook `tmp.ipynb` in `cog/agent` showcasing the agent ran on a sample question from the benchmark
  - [x] Add print statements for all calls to the LLM for easier debugging + I can easily verify the outputs
- [x] Request a review from @alckasoc 

_If there is any additional logic for how CRITIC is tested on AmbigNQ (refer to the paper's [repo](https://github.com/microsoft/ProphetNet/tree/master/CRITIC)), include these specifications in the PR description._

Feel free to ask me questions on slack if you're confused! Good luck!

**Comment by jsgage7** [comment]
@alckasoc Commenting for assignment
